const PHONE='201005859161';
const catalog=[
['السماعات','Samsung','Galaxy Buds','🎧'],['السماعات','Apple','AirPods','🎧'],['السماعات','JBL','Bluetooth Headset','🎧'],['السماعات','Anker','Soundcore','🎧'],
['الساعات','Samsung','Galaxy Watch','⌚'],['الساعات','Apple','Apple Watch','⌚'],['الساعات','Huawei','Smart Watch','⌚'],['الساعات','Xiaomi','Smart Watch','⌚'],
['الجرابات','Spigen','Tough Armor Case','📱'],['الجرابات','Apple','MagSafe Case','📱'],['الجرابات','Samsung','Silicone Case','📱'],['الجرابات','ESR','Protection Case','📱'],
['الاسكرينات','Orange Store','Tempered Glass','🛡️'],['الاسكرينات','Orange Store','Privacy Glass','🛡️'],['الحماية','ESR','Camera Lens Protector','🛡️'],
['الشحن','Samsung','Fast Charger','⚡'],['الشحن','Anker','GaN Charger','⚡'],['الشحن','UGREEN','Type-C Cable','⚡'],['الشحن','Baseus','Power Bank','🔋'],
['الألعاب','GameSir','Gaming Controller','🎮'],['الألعاب','Redragon','Gaming Mouse','🎮'],['الألعاب','Razer','Gaming Keyboard','🎮'],
['قطع الغيار','Orange Store','Display Replacement','🔧'],['قطع الغيار','Orange Store','Battery Replacement','🔋'],['أدوات الصيانة','Orange Store','Repair Tool Kit','🧰']
];
const products=Array.from({length:10000},(_,i)=>{const t=catalog[i%catalog.length];return{id:i+1,category:t[0],brand:t[1],name:`${t[2]} ${String(i+1).padStart(4,'0')}`,icon:t[3]}});
const grid=document.getElementById('productGrid'),search=document.getElementById('searchInput'),cat=document.getElementById('categoryFilter'),brand=document.getElementById('brandFilter'),more=document.getElementById('loadMore'),info=document.getElementById('resultInfo');
[...new Set(products.map(p=>p.category))].forEach(x=>cat.insertAdjacentHTML('beforeend',`<option>${x}</option>`));
[...new Set(products.map(p=>p.brand))].forEach(x=>brand.insertAdjacentHTML('beforeend',`<option>${x}</option>`));
let filtered=products,shown=0;const PAGE=40;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(p){const msg=encodeURIComponent(`السلام عليكم 👋\nأريد الاستفسار عن المنتج:\n📦 ${p.name}\n🏷️ ${p.brand}\n📂 ${p.category}\nهل المنتج متوفر؟`);const google=`https://www.google.com/search?tbm=isch&q=${encodeURIComponent(p.name+' '+p.brand)}`;return `<article class="product-card"><div class="product-visual">${p.icon}<small>3D</small></div><span class="brand">${esc(p.brand)}</span><h3>${esc(p.name)}</h3><div class="category">${esc(p.category)}</div><div class="status">● متوفر</div><div class="actions"><button class="btn3d" onclick="showDetails(${p.id})">◉ التفاصيل 3D</button><button class="btn3d alt" onclick="window.open('${google}','_blank')">🖼 الصور</button><button class="btn3d alt" onclick="window.open('https://wa.me/${PHONE}?text=${msg}','_blank')">💬 استفسار</button><a class="btn3d alt call" href="tel:01005859161">📞 اتصال</a></div></article>`}
function render(reset=true){const q=search.value.trim().toLowerCase();filtered=products.filter(p=>(!q||`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q))&&(cat.value==='all'||p.category===cat.value)&&(brand.value==='all'||p.brand===brand.value));if(reset){shown=0;grid.innerHTML=''}const part=filtered.slice(shown,shown+PAGE);grid.insertAdjacentHTML('beforeend',part.map(card).join(''));shown+=part.length;info.textContent=`عرض ${shown} من ${filtered.length} منتج`;more.disabled=shown>=filtered.length;more.textContent=more.disabled?'تم عرض كل المنتجات':`تحميل المزيد (${Math.min(PAGE,filtered.length-shown)})`}
function showDetails(id){const p=products[id-1];const msg=encodeURIComponent(`السلام عليكم 👋 أريد تفاصيل المنتج ${p.name} من قسم ${p.category}`);const w=window.open('','_blank','width=500,height=600');w.document.write(`<body style="margin:0;background:#07090f;color:white;font-family:Arial;text-align:center;padding:35px"><div style="font-size:100px">${p.icon}</div><h1 style="color:#ff7800">${esc(p.name)}</h1><h3>${esc(p.brand)}</h3><p>${esc(p.category)}</p><p>● متوفر</p><p>السعر غير معروض</p><a href="https://wa.me/${PHONE}?text=${msg}" style="display:inline-block;padding:15px 25px;background:#ff6900;color:white;border-radius:14px;text-decoration:none;font-weight:bold">💬 استفسار عبر واتساب</a></body>`)}
[search,cat,brand].forEach(e=>e.addEventListener('input',()=>render(true)));more.addEventListener('click',()=>render(false));render();
